#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 6.1.2 effective-5.10 (swiftlang-6.1.2.1.2 clang-1700.0.13.5)
#ifndef XSOLLAMOBILESDK_SWIFT_H
#define XSOLLAMOBILESDK_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import Foundation;
@import ObjectiveC;
@import UIKit;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="XsollaMobileSDK",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSString;
@class NSBundle;
@class NSCoder;
/// A view controller used as a container for presenting other view controllers with specific configurations.
SWIFT_CLASS("_TtC15XsollaMobileSDK11ContainerVC")
@interface ContainerVC : UIViewController
- (void)viewDidLoad;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class UIWindowScene;
/// A custom UIWindow subclass used for presenting view controllers in a specific manner.
SWIFT_CLASS("_TtC15XsollaMobileSDK15ContainerWindow")
@interface ContainerWindow : UIWindow
- (nonnull instancetype)initWithWindowScene:(UIWindowScene * _Nonnull)windowScene OBJC_DESIGNATED_INITIALIZER SWIFT_AVAILABILITY(ios,introduced=13.0);
- (nonnull instancetype)initWithFrame:(CGRect)frame OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
@end

@class SKPaymentSettings;
@class XMAccessTokenInfo;
enum XMSocialNetworkProvider : NSInteger;
/// Provides functions for managing user authentication through Xsolla
SWIFT_CLASS_NAMED("LoginManager")
@interface XMLoginManager : NSObject
/// Shared LoginManager singleton.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) XMLoginManager * _Nonnull shared;)
+ (XMLoginManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
+ (void)setShared:(XMLoginManager * _Nonnull)value;
/// [BETA] Shows Xsolla Login Widget to authenticate
/// \param settings The payment settings.
///
/// \param completion A completion handler called with the result of the authentication.
///
- (void)authWithXsollaWidgetWithSettings:(SKPaymentSettings * _Nonnull)settings completion:(void (^ _Nonnull)(XMAccessTokenInfo * _Nullable, NSError * _Nullable))completion;
/// [BETA] Shows Xsolla Account Login Widget to authenticate
/// \param settings The payment settings.
///
/// \param completion A completion handler called with the result of the authentication.
///
- (void)authWithXsollaAccountWithSettings:(SKPaymentSettings * _Nonnull)settings completion:(void (^ _Nonnull)(XMAccessTokenInfo * _Nullable, NSError * _Nullable))completion;
/// [BETA] Returns Xsolla Login Widget user’s info if already authenticated, refreshes it if it’s expired.
/// \param settings The payment settings.
///
///
/// throws:
/// An error if the token is missing or refresh fails.
- (void)loadWidgetUserInfo:(SKPaymentSettings * _Nonnull)settings completionHandler:(void (^ _Nonnull)(NSError * _Nullable))completionHandler SWIFT_AVAILABILITY(ios,introduced=13.0);
/// [BETA] Returns Xsolla Login Widget token if already authenticated, refreshes it if it’s expired.
/// \param settings The payment settings.
///
/// \param completion A completion handler called with the result of the operation.
///
- (void)loadWidgetAuthTokenWithSettings:(SKPaymentSettings * _Nonnull)settings completion:(void (^ _Nonnull)(XMAccessTokenInfo * _Nullable, NSError * _Nullable))completion;
/// [BETA] Returns Xsolla Login Widget token if already authenticated, refreshes it if it’s expired.
/// \param token The access token information.
///
/// \param settings The payment settings.
///
/// \param completion A completion handler called with the result of the operation.
///
- (void)refreshWidgetAuthToken:(XMAccessTokenInfo * _Nonnull)token settings:(SKPaymentSettings * _Nonnull)settings completion:(void (^ _Nonnull)(XMAccessTokenInfo * _Nullable, NSError * _Nullable))completion;
/// [BETA] Returns Xsolla Login Widget user’s info if already authenticated, refreshes it if it’s expired.
/// \param settings The payment settings.
///
/// \param completion A completion handler called with the result of the operation.
///
- (void)loadWidgetUserInfoWithSettings:(SKPaymentSettings * _Nonnull)settings completion:(void (^ _Nonnull)(XMAccessTokenInfo * _Nullable, NSError * _Nullable))completion;
/// [BETA] Clears a token that was cached by logging in through the Xsolla Widget, based on login project id and oAuth2 client id from the provided settings.
/// \param settings The payment settings.
///
- (void)clearWidgetAuthTokenWithSettings:(SKPaymentSettings * _Nonnull)settings;
/// Authenticates with a social network provider using the provided access token (Objective-C compatible).
/// \param settings The payment settings.
///
/// \param provider The social network provider.
///
/// \param socialAccessToken The social network access token.
///
/// \param completion A completion handler called with the result of the authentication.
///
- (void)authWithSocialProviderWithSettings:(SKPaymentSettings * _Nonnull)settings provider:(enum XMSocialNetworkProvider)provider socialAccessToken:(NSString * _Nonnull)socialAccessToken completion:(void (^ _Nonnull)(XMAccessTokenInfo * _Nullable, NSError * _Nullable))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class XMRetryPolicy;
/// Container for retry policy overrides for different operations.
/// Allows configuring custom retry behavior for specific operations while maintaining
/// a default policy for operations that don’t have specific overrides.
SWIFT_CLASS_NAMED("RetryPolicies")
@interface XMRetryPolicies : NSObject
/// Default retry profile override for all operations.
@property (nonatomic, strong) XMRetryPolicy * _Nullable defaultRetryProfileOverride;
/// Retry profile override for pending order status queries.
@property (nonatomic, strong) XMRetryPolicy * _Nullable pendingOrderStatusQueryRetryProfileOverride;
/// Retry profile override for create order operations.
@property (nonatomic, strong) XMRetryPolicy * _Nullable createOrderRetryProfileOverride;
/// Retry profile override for authenticate operations.
@property (nonatomic, strong) XMRetryPolicy * _Nullable authenticateRetryProfileOverride;
/// Retry profile override for query products operations.
@property (nonatomic, strong) XMRetryPolicy * _Nullable queryProductsRetryProfileOverride;
/// Retry profile override for query purchases operations.
@property (nonatomic, strong) XMRetryPolicy * _Nullable queryPurchasesRetryProfileOverride;
/// Retry profile override for consume purchases operations.
@property (nonatomic, strong) XMRetryPolicy * _Nullable consumePurchasesRetryProfileOverride;
/// Creates an empty retry policies container.
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum XMRetryPolicyType : NSInteger;
@class NSNumber;
/// Represents a retry policy configuration.
/// Supports both uniform and exponential backoff retry strategies.
SWIFT_CLASS_NAMED("RetryPolicy")
@interface XMRetryPolicy : NSObject
/// The type of retry policy.
@property (nonatomic, readonly) enum XMRetryPolicyType type;
/// The maximum number of retry attempts.
@property (nonatomic, readonly) NSInteger maxNumAttempts;
/// Creates a uniform retry policy.
/// \param maxNumAttempts The maximum number of retry attempts.
///
/// \param intervalMillis The interval in milliseconds between retries.
///
- (nonnull instancetype)initWithUniform:(NSInteger)maxNumAttempts intervalMillis:(NSInteger)intervalMillis OBJC_DESIGNATED_INITIALIZER;
/// Creates an exponential backoff retry policy.
/// \param maxNumAttempts The maximum number of retry attempts.
///
/// \param baseIntervalMillis The base interval in milliseconds.
///
/// \param maxIntervalMillis Optional maximum interval in milliseconds.
///
/// \param maxRandomExtraDelayMillis Optional maximum random extra delay in milliseconds.
///
- (nonnull instancetype)initWithExponentialBackoff:(NSInteger)maxNumAttempts baseIntervalMillis:(NSInteger)baseIntervalMillis maxIntervalMillis:(NSNumber * _Nullable)maxIntervalMillis maxRandomExtraDelayMillis:(NSNumber * _Nullable)maxRandomExtraDelayMillis;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents the type of retry policy.
typedef SWIFT_ENUM_NAMED(NSInteger, XMRetryPolicyType, "RetryPolicyType", open) {
/// Uniform retry policy with fixed intervals.
  XMRetryPolicyTypeUniform = 0,
/// Exponential backoff retry policy.
  XMRetryPolicyTypeExponentialBackoff = 1,
};

/// Represents error codes for the Xsolla Mobile SDK.
/// These codes identify specific error conditions that can occur.
typedef SWIFT_ENUM(NSInteger, SKError, open) {
/// An unknown error occurred.
  SKErrorUnknown = 0,
/// The client is invalid.
  SKErrorClientInvalid = 1,
/// The payment was cancelled by the user.
  SKErrorPaymentCancelled = 2,
/// Error code indicating that one of the payment parameters was not recognized.
  SKErrorPaymentInvalid = 3,
  SKErrorAborted = 1000,
};

/// Represents the log level for the SDK.
/// Controls the verbosity of logging.
typedef SWIFT_ENUM(NSInteger, SKLogLevel, open) {
/// Most detailed logging level.
  SKLogLevelVerbose = 0,
/// Logs significant events.
  SKLogLevelEvent = 1,
/// Logs debug information.
  SKLogLevelDebug = 2,
/// Logs general information.
  SKLogLevelInfo = 3,
/// Logs noteworthy occurrences.
  SKLogLevelNotice = 4,
/// Logs potential issues.
  SKLogLevelWarning = 5,
/// Logs errors.
  SKLogLevelError = 6,
};

@class NSData;
@class SKXProduct;
/// Represents a payment for a product in the Xsolla Mobile SDK.
/// Contains information about the product being purchased and payment details.
SWIFT_CLASS_NAMED("SKPayment")
@interface SKXPayment : NSObject
/// The product identifier for the payment.
/// This is a unique string that identifies the product being purchased.
@property (nonatomic, readonly, copy) NSString * _Nonnull productIdentifier;
/// The quantity of the product to purchase.
/// Always returns 1 in the current implementation.
@property (nonatomic, readonly) NSInteger quantity;
/// Additional request data for the payment.
/// Returns nil in the current implementation.
@property (nonatomic, readonly, copy) NSData * _Nullable requestData;
/// The application username associated with the payment.
/// Returns nil in the current implementation.
@property (nonatomic, readonly, copy) NSString * _Nullable applicationUsername;
/// Custom payload for the payment.
/// Can be used to pass additional information with the payment.
@property (nonatomic, copy) NSString * _Nullable customPayload;
/// Transaction external id. https://developers.xsolla.com/doc/pay-station/references/faq/#faq_payments_q_new_transaction_external_id
@property (nonatomic, copy) NSString * _Nullable externalIdentifier;
/// Payment method ID. Overrides payment method from settings. It determines the display of currency in the payment interface, as some payment methods may only support certain currencies.
/// https://developers.xsolla.com/api/shop-builder/operation/create-order-with-item/#!path=settings/payment_method&t=request
@property (nonatomic, strong) NSNumber * _Nullable paymentMethodId;
/// Initializes a new instance of <code>SKPayment</code>.
/// \param product The product to purchase.
///
- (nonnull instancetype)initWithProduct:(SKXProduct * _Nonnull)product OBJC_DESIGNATED_INITIALIZER;
/// Creates a new payment with the specified product.
/// \param product The product to purchase.
///
///
/// returns:
/// A new instance of <code>SKPayment</code>.
+ (nonnull instancetype)paymentWithProduct:(SKXProduct * _Nonnull)product SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// A mutable version of SKPayment.
/// This class is maintained for compatibility with Apple’s StoreKit API.
SWIFT_CLASS_NAMED("SKMutablePayment")
@interface SKXMutablePayment : SKXPayment
- (nonnull instancetype)initWithProduct:(SKXProduct * _Nonnull)product OBJC_DESIGNATED_INITIALIZER;
@end

/// Represents the platform for payments in the Xsolla Mobile SDK.
/// Different platforms may have different payment processing requirements.
typedef SWIFT_ENUM(NSInteger, SKPaymentPlatform, open) {
/// App Store payments platform.
  SKPaymentPlatformAppStore = 0,
/// Standalone payments platform.
  SKPaymentPlatformStandalone = 1,
/// Other payments platform.
  SKPaymentPlatformOther = 2,
};

@protocol SKXPaymentTransactionObserver;
@class SKXPaymentTransaction;
@class NSURL;
@class XMTokenPayment;
/// Manages a queue of payments and transactions in the Xsolla Mobile SDK.
/// This is the central class for processing payments and handling transactions.
SWIFT_CLASS_NAMED("SKPaymentQueue")
@interface SKXPaymentQueue : NSObject
/// The transaction observers for the payment queue.
/// These observers receive callbacks when transactions are updated.
@property (nonatomic, readonly, copy) NSArray<id <SKXPaymentTransactionObserver>> * _Nonnull transactionObservers;
/// The transactions in the payment queue.
/// Contains all current transactions being processed.
@property (nonatomic, readonly, copy) NSArray<SKXPaymentTransaction *> * _Nonnull transactions;
/// Returns the default payment queue.
/// This is the singleton instance used for all payment operations.
+ (SKXPaymentQueue * _Nonnull)defaultQueue SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
/// Starts the payment queue with the specified settings.
/// Must be called before using the payment system.
/// \param settings The payment settings to use.
///
- (void)startWithSettings:(SKPaymentSettings * _Nonnull)settings;
/// Adds a transaction observer to the payment queue.
/// The observer will receive callbacks when transactions are updated.
/// \param observer The observer to add.
///
- (void)addTransactionObserver:(id <SKXPaymentTransactionObserver> _Nonnull)observer;
/// Removes a transaction observer from the payment queue.
/// The observer will no longer receive callbacks.
/// \param observer The observer to remove.
///
- (void)removeTransactionObserver:(id <SKXPaymentTransactionObserver> _Nonnull)observer;
/// Adds a payment to the payment queue.
/// This initiates the purchase process for the specified product.
/// \param payment The payment to add.
///
- (void)addPayment:(SKXPayment * _Nonnull)payment;
/// Finishes a transaction in the payment queue.
/// This should be called after a transaction has been processed.
/// \param transaction The transaction to finish.
///
- (void)finishTransaction:(SKXPaymentTransaction * _Nonnull)transaction;
/// Cancels the currently active transaction in the payment queue.
/// This will abort any ongoing payment process, cancel network requests, and mark the transaction as failed with an aborted error.
///
/// returns:
/// <code>true</code> if a transaction was cancelled, <code>false</code> if there was no active transaction to cancel.
- (BOOL)cancelTransaction SWIFT_WARN_UNUSED_RESULT;
/// Restores completed transactions.
/// This allows users to restore previously purchased non-consumable products.
- (void)restoreCompletedTransactions;
/// Always returns true. Compatibility method.
/// Checks if payments can be made.
///
/// returns:
/// A boolean indicating if payments can be made.
+ (BOOL)canMakePayments SWIFT_WARN_UNUSED_RESULT;
/// Sets up engine analytics for the specified engine and version.
/// Used to track which game engine is using the SDK.
/// \param engine The engine to set up analytics for (e.g., “Unity”, “Unreal”).
///
/// \param version The version of the engine.
///
- (void)setupEngineAnalyticsFor:(NSString * _Nonnull)engine version:(NSString * _Nonnull)version;
/// Checks if the app is running thorugh an alternative iOS app distribution or web.
/// Alternative billing is only available in third-party marketplaces, not in the official App Store (in EU).
/// \param completion A closure that gets called with the result (true if in alternative distribution).
///
+ (void)checkIfRunningInAlternativeDistributionWithCompletion:(void (^ _Nonnull)(BOOL))completion;
/// Retrieves the current Storefront’s three-letter country code to enhance payment availability management.
/// The value is stored in cache and the completion handler is called as soon as it’s initially loaded.
/// \param completion A closure that receives the result.
///
+ (void)loadCurrentStorefrontCountryCodeWithCompletion:(void (^ _Nonnull)(NSString * _Nullable))completion;
/// Validates a transaction on the client side.
/// This can be used to verify that a transaction is valid.
/// \param transaction The transaction to validate.
///
/// \param completion A closure that gets called with the validation result.
///
- (void)validateTransaction:(SKXPaymentTransaction * _Nonnull)transaction completion:(void (^ _Nonnull)(BOOL, NSError * _Nullable))completion;
/// Opens a URL for the payment queue.
/// If UIApplicationDelegate swizzling is disabled, this function should be called from openUrl or from didFinishLaunching
/// \param url The URL to open.
///
///
/// returns:
/// A boolean indicating if the URL was opened.
- (BOOL)openWithUrl:(NSURL * _Nonnull)url SWIFT_WARN_UNUSED_RESULT;
/// Returns the supported interface orientations for the specified window.
/// If UIApplicationDelegate swizzling is disabled, this function should be called from supportedOrientationsForWindow
/// \param window The window to get the supported orientations for.
///
///
/// returns:
/// The supported interface orientations.
- (UIInterfaceOrientationMask)supportedInterfaceOrientationsForWindow:(UIWindow * _Nullable)window SWIFT_WARN_UNUSED_RESULT;
/// Returns the current login token used for requests.
/// This token is used to authenticate the user with the Xsolla backend.
@property (nonatomic, readonly, copy) NSString * _Nullable currentLoginToken;
/// Initiates a token-only purchase flow using the provided Paystation token.
/// This method serves as an alternative entry point for initiating a purchase without needing to create a traditional SKPaymentTransaction from an SKPayment.
/// Instead, the purchase is started by directly supplying a valid Paystation token along with a sandbox flag.
/// Internally, the token and sandbox flag are passed to the payments manager, which handles creating the appropriate transaction and continuing
/// the purchase flow (including UI presentation and callbacks).
/// \param token A string representing the externally generated Paystation token.
///
/// \param isSandbox A Boolean value indicating whether the token is for a sandbox (testing) environment.
///
/// \param Note Ensure that the SDK’s settings have already been configured before calling this method.
///
- (void)purchaseWithPaystationToken:(NSString * _Nonnull)token isSandbox:(BOOL)isSandbox;
/// Initiates a token-only purchase using a <code>TokenPayment</code> value.
/// If <code>isSandbox</code> is <code>nil</code>, the current value from <code>SKPaymentSettings.useSandbox</code> will be used.
/// The <code>allowFinishedWithoutOrderId</code> flag is per-transaction and controls whether a finished
/// status from Pay Station is sufficient to complete the purchase without an <code>order_id</code>.
/// See token creation API: https://developers.xsolla.com/api/shop-builder/operation/admin-create-payment-token/
- (void)purchaseWithTokenPayment:(XMTokenPayment * _Nonnull)payment;
/// Initiates a purchase using the Web Shop by specifying the product’s SKU.
/// This method attempts to construct a Web Shop URL and open it based on previously configured settings
/// via the <code>setupWebShop(...)</code> method. It supports initiating purchases outside the standard SDK flow,
/// enabling integration with external purchase systems like Xsolla’s Web Shop.
/// important:
///
/// <ul>
///   <li>
///     Requires the Web Shop to be configured via <code>setupWebShop(...)</code> in settings.
///   </li>
///   <li>
///     If the Web Shop URL is invalid or not configured, the method will not proceed and returns <code>false</code>.
///   </li>
/// </ul>
/// \param sku The SKU of the product to purchase from the Web Shop catalog.
///
///
/// returns:
/// <code>true</code> if the Web Shop was successfully opened, <code>false</code> otherwise.
- (BOOL)purchaseWithSKU:(NSString * _Nonnull)sku SWIFT_WARN_UNUSED_RESULT;
@end

enum SKPaystationTheme : NSInteger;
enum SKPaystationSize : NSInteger;
@class UIColor;
@class NSLocale;
@class PaystationDomainConfiguration;
/// Represents the settings for payments in the Xsolla Mobile SDK.
/// Contains configuration options for the payment system.
SWIFT_CLASS("_TtC15XsollaMobileSDK17SKPaymentSettings")
@interface SKPaymentSettings : NSObject
/// The platform for payments.
@property (nonatomic) enum SKPaymentPlatform platform;
/// The theme ID for the paystation UI.
@property (nonatomic) enum SKPaystationTheme paystationUIThemeId;
/// Custom theme ID for the paystation UI.
@property (nonatomic, copy) NSString * _Nullable paystationUIThemeCustomId;
/// The size for the paystation UI.
@property (nonatomic) enum SKPaystationSize paystationUISize;
/// The tint color for the web view bar.
@property (nonatomic, strong) UIColor * _Nullable webViewBarTintColor;
/// The tint color for the web view controls.
@property (nonatomic, strong) UIColor * _Nullable webViewControlTintColor;
/// Application ID from <a href="https://publisher.xsolla.com/">Publisher Account</a>.
/// You will get it after sending the request to enable the OAuth 2.0 protocol.
@property (nonatomic) NSInteger oAuth2ClientId;
/// Project ID.
/// The unique identifier for your project in the Xsolla system.
@property (nonatomic, readonly) NSInteger projectId;
/// Login projects have separate IDs in the form of UUID.
/// This is used for authentication with the Xsolla Login service.
@property (nonatomic, copy) NSString * _Nullable loginProjectId;
/// The default scope for login.
/// Set to “offline” by default to enable refresh tokens.
@property (nonatomic, copy) NSString * _Nonnull defaultLoginScope;
/// Used for login. <code>https://login.xsolla.com/api/blank</code> by default
/// The URL that the login process will redirect to after completion.
@property (nonatomic, copy) NSString * _Nonnull redirectUrl;
/// Redirect scheme for returning back to the game after the payment. <code>$(PRODUCT_BUNDLE_IDENTIFIER)://xsollaconfirm/payment</code> by default.
/// This URL scheme must be registered in your app’s Info.plist.
@property (nonatomic, copy) NSString * _Nonnull paymentsRedirectUrl;
/// Redirect scheme for returning from generic web views.
/// This URL scheme must be registered in your app’s Info.plist.
@property (nonatomic, copy) NSString * _Nonnull webViewDismissRedirectUrl;
/// Back to the game button caption on payment finish.
/// The text displayed on the button that returns the user to the game.
@property (nonatomic, copy) NSString * _Nullable redirectButtonCaption;
/// Seconds until payment redirects back to the game after finishing.
/// Controls the automatic redirect timeout.
@property (nonatomic) NSInteger redirectTimeOut;
/// Root View Controller that will be used to show Payment View Controller.
/// This is the view controller that the payment UI will be presented from.
@property (nonatomic, strong) UIViewController * _Nullable rootViewController;
/// Set to true to enable the SDK.
/// The SDK will not process payments if this is false.
@property (nonatomic) BOOL enablePayments;
/// By default <code>true</code> and will swizzle UIApplicationDelegate to handle payments redirect URL that comes from external sources. Won’t work properly with SwiftUI’s AppDelegate.
/// Controls whether the SDK automatically handles URL redirects.
@property (nonatomic) BOOL swizzleUrlHandling;
/// Will use Inventory to try and restore purchases, consuming them them in <code>finishTransaction</code>.
/// Controls whether local purchase restoration is used.
@property (nonatomic) BOOL useLocalPurchaseRestoration;
/// Will use Xsolla Events API to track and restore purchases instead of the Inventory API.
@property (nonatomic) BOOL useEventsApiForPurchaseRestoration;
/// Use Sandbox for payments.
/// Set to true for testing payments in a sandbox environment.
@property (nonatomic) BOOL useSandbox;
/// Provide custom login token from other means of authentication done outside.
/// If set, this token will be used instead of performing a login flow.
@property (nonatomic, copy) NSString * _Nullable customLoginToken;
/// Whether to use login token when fetching products, to apply personalization.
@property (nonatomic) BOOL fetchPersonalizedProducts;
/// Provide custom user id to login with.
/// If set, this user ID will be used for authentication.
@property (nonatomic, copy) NSString * _Nullable customUserId;
/// Provide a custom tracking identifier that will be passed to payments.
@property (nonatomic, copy) NSString * _Nullable trackingId;
/// Payment method ID. It determines the display of currency in the payment interface, as some payment methods may only support certain currencies.
/// https://developers.xsolla.com/api/shop-builder/operation/create-order-with-item/#!path=settings/payment_method&t=request
@property (nonatomic, strong) NSNumber * _Nullable paymentMethodId;
/// Obj-C compatible bridge for <code>visiblePaymentLogo</code>.
@property (nonatomic, strong) NSNumber * _Nullable visiblePaymentLogoValue;
/// Response language. Two-letter lowercase language code per ISO 639-1. Default <code>en</code>.
@property (nonatomic, copy) NSString * _Nullable languageCode;
/// Two-letter uppercase country code per ISO 3166-1 alpha-2. Shows regional prices and restrictions for a catalog if those were specified while creating an item. If you do not specify the country explicitly, it will be set based on user’s IP address.
/// Controls the country used for pricing and restrictions.
@property (nonatomic, copy) NSString * _Nullable countryCode;
/// Language and country based on locale.
/// Provides a convenient way to set both language and country codes.
@property (nonatomic, copy) NSLocale * _Nullable locale;
/// Opens paystation out of the app in Safari or other system browser.
/// If true, the payment UI will open in an external browser.
@property (nonatomic) BOOL openExternalBrowser;
/// Wether to use BuyButton solution - https://xsolla.com/mobile-buy-button
@property (nonatomic) BOOL useBuyButtonSolution;
/// Whether to use simple mode and skip login and other initialization flows. Might be used with Web Shop purchases or purchases initiated by the token.
@property (nonatomic) BOOL useSimpleMode;
/// When set, will open Web Shop instead of PayStation.
@property (nonatomic, copy) NSURL * _Nullable webshopUrl;
/// User Id that will be passed to the Web Shop.
@property (nonatomic, copy) NSString * _Nullable webshopUserId;
/// Redirect scheme for returning back to the game after the payment in Web Shop. <code>$(PRODUCT_BUNDLE_IDENTIFIER)://xsollaconfirm/webshop</code> by default.
/// This URL scheme must be registered in your app’s Info.plist.
/// SDK doesn’t handle this in any way.
@property (nonatomic, copy) NSString * _Nonnull webshopRedirectUrl;
/// Lock Paystation display to this orientation.
/// Controls the allowed orientations for the payment UI.
@property (nonatomic) UIInterfaceOrientationMask paystationOrientation;
/// Allow using invisible container controller to force the orientation.
/// Controls whether a container controller is used to enforce orientation.
/// This is enabled on iOS 26 and above by default.
@property (nonatomic) BOOL allowUsingContainerController;
/// Shows Paystation as a popover on iPhone.
/// Controls whether the payment UI is shown as a popover on iPhone.
@property (nonatomic) BOOL showPaystationAsPopover;
/// Don’t apply orientation logic to the iPad.
/// If true, orientation restrictions are not applied on iPad.
@property (nonatomic) BOOL skipOrientationForPad;
/// Paystation presentation style for iPad.
/// Controls how the payment UI is presented on iPad.
@property (nonatomic) UIModalPresentationStyle paystationPresentationForPad;
/// Should we cache a token returned by the widget login.
/// Controls whether login tokens are cached.
@property (nonatomic) BOOL cacheWidgetToken;
/// Obj-C compatible bridge for <code>collectPartnerEventEmailConsent</code>.
@property (nonatomic, strong) NSNumber * _Nullable collectPartnerEventEmailConsentValue;
@property (nonatomic) enum SKLogLevel logLevel;
/// Retry policies configuration for network operations.
/// Allows customizing retry behavior for different operations (authentication, order creation, etc.).
@property (nonatomic, strong) XMRetryPolicies * _Nullable retryPolicies;
/// Optional container with custom Pay Station domain configuration.
@property (nonatomic, strong) PaystationDomainConfiguration * _Nullable paystationDomainConfiguration;
/// Configures custom Pay Station domains.
/// \param productionDomain Production domain URL (required).
///
/// \param sandboxDomain Sandbox domain URL (optional). If <code>nil</code>, default <code>sandbox-secure.xsolla.com</code> will be used.
///
- (void)setupCustomPaystationDomainWithProductionDomain:(NSURL * _Nonnull)productionDomain sandboxDomain:(NSURL * _Nullable)sandboxDomain;
/// Initializes a new instance of <code>SKPaymentSettings</code>.
/// \param projectId The project ID.
///
/// \param loginProjectId The login project ID.
///
/// \param platform The payment platform.
///
/// \param paystationUIThemeId The theme for the paystation UI.
///
/// \param paystationUISize The size for the paystation UI.
///
/// \param oAuth2ClientId The OAuth 2.0 client ID.
///
- (nonnull instancetype)initWithProjectId:(NSInteger)projectId loginProjectId:(NSString * _Nullable)loginProjectId platform:(enum SKPaymentPlatform)platform paystationUIThemeId:(enum SKPaystationTheme)paystationUIThemeId paystationUISize:(enum SKPaystationSize)paystationUISize oAuth2ClientId:(NSInteger)oAuth2ClientId OBJC_DESIGNATED_INITIALIZER;
/// Convenience initializer for <code>SKPaymentSettings</code>.
/// \param projectId The project ID.
///
/// \param loginProjectId The login project ID.
///
- (nonnull instancetype)initWithProjectId:(NSInteger)projectId loginProjectId:(NSString * _Nonnull)loginProjectId;
/// Convenience initializer for <code>SKPaymentSettings</code>.
/// \param projectId The project ID.
///
/// \param oAuth2ClientId The OAuth 2.0 client ID.
///
- (nonnull instancetype)initWithProjectId:(NSInteger)projectId oAuth2ClientId:(NSInteger)oAuth2ClientId;
/// Configures the payment settings to use the Web Shop Buy Button flow instead of the default PayStation.
/// This method sets up the SDK to initiate purchases via a Web Shop URL. It enables <code>useSimpleMode</code>
/// and configures the related parameters such as the shop URL, user ID, redirect URL, and whether
/// to open the Web Shop externally or within the app.
/// \param url The base URL of the Web Shop. Assigned to <code>webshopUrl</code>.
///
/// \param userId The user identifier that will be passed to the Web Shop. Assigned to <code>webshopUserId</code>.
///
/// \param returnUrl (Optional) The redirect URL that the Web Shop will use to return to the game after purchase.
/// If provided, it overrides the default <code>webshopRedirectUrl</code>.
///
/// \param openExternally Whether to open the Web Shop in an external browser (e.g., Safari). Default is <code>true</code>.
/// Assigned to <code>openExternalBrowser</code>.
///
- (void)setupBuyButtonWebShopWithUrl:(NSURL * _Nonnull)url userId:(NSString * _Nonnull)userId returnUrl:(NSString * _Nullable)returnUrl openExternally:(BOOL)openExternally;
/// Sets the social provider token using Objective-C compatible enum.
/// \param provider The social network provider (Objective-C compatible).
///
/// \param accessToken The social network access token.
///
- (void)setSocialProviderTokenWithProvider:(enum XMSocialNetworkProvider)provider accessToken:(NSString * _Nonnull)accessToken;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class NSDate;
enum SKPaymentTransactionState : NSInteger;
/// Represents a payment transaction in the Xsolla Mobile SDK.
/// Contains information about a payment and its current state.
SWIFT_CLASS_NAMED("SKPaymentTransaction")
@interface SKXPaymentTransaction : NSObject
/// The payment associated with this transaction.
@property (nonatomic, readonly, strong) SKXPayment * _Nonnull payment;
/// The unique identifier for the transaction.
/// Used to track the transaction in the payment system.
@property (nonatomic, readonly, copy) NSString * _Nullable transactionIdentifier;
/// The date when the transaction occurred.
@property (nonatomic, readonly, copy) NSDate * _Nullable transactionDate;
/// The original transaction, if this transaction is a restore or renewal.
@property (nonatomic, readonly, strong) SKXPaymentTransaction * _Nullable originalTransaction;
/// Any error that occurred during the transaction.
@property (nonatomic, readonly) NSError * _Nullable error;
/// The transaction receipt data.
/// Contains information that can be used to verify the transaction.
@property (nonatomic, readonly, copy) NSData * _Nullable transactionReceipt;
/// The current state of the transaction.
@property (nonatomic, readonly) enum SKPaymentTransactionState transactionState;
/// This is Xsolla invoice id which user gets in the email and can ask for support or refund.
@property (nonatomic, readonly, copy) NSString * _Nullable invoiceIdentifier;
/// This is user id which actually finished the purchase, used for validation.
@property (nonatomic, readonly, copy) NSString * _Nullable userIdentifier;
- (BOOL)cancel SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

enum SKXPaymentTransactionPaystationEvent : NSInteger;
/// Protocol for observing payment transactions in the Xsolla Mobile SDK.
/// Implement this protocol to receive callbacks when transactions are updated or removed.
SWIFT_PROTOCOL_NAMED("SKPaymentTransactionObserver")
@protocol SKXPaymentTransactionObserver
@optional
/// Called when the payment queue updates transactions.
/// This method is invoked when transactions change state.
/// \param queue The payment queue that updated the transactions.
///
/// \param updatedTransactions The transactions that were updated.
///
- (void)paymentQueue:(SKXPaymentQueue * _Nonnull)_ updatedTransactions:(NSArray<SKXPaymentTransaction *> * _Nonnull)updatedTransactions;
/// Called when the payment queue removes transactions.
/// This method is invoked when transactions are removed from the queue.
/// \param queue The payment queue that removed the transactions.
///
/// \param removedTransactions The transactions that were removed.
///
- (void)paymentQueue:(SKXPaymentQueue * _Nonnull)_ removedTransactions:(NSArray<SKXPaymentTransaction *> * _Nonnull)removedTransactions;
- (void)paymentQueueDidChangeStorefront:(SKXPaymentQueue * _Nonnull)_;
/// Called when Pay Station emits lifecycle events for a specific transaction.
/// \param queue The payment queue that manages the transaction.
///
/// \param event The lifecycle event reported by the Pay Station UI.
///
/// \param transaction The transaction associated with the event.
///
- (void)paymentQueue:(SKXPaymentQueue * _Nonnull)queue event:(enum SKXPaymentTransactionPaystationEvent)event for:(SKXPaymentTransaction * _Nonnull)transaction;
/// Called when SDK did login, so that purchases and personalized items can be started. Isn’t called if custom login token is set.
- (void)paymentQueueDidLogin:(SKXPaymentQueue * _Nonnull)queue;
@end

/// Represents lifecycle events emitted by the Pay Station UI for a specific transaction.
/// Observers can listen to these events to update analytics or UI outside of the purchase flow.
typedef SWIFT_ENUM_NAMED(NSInteger, SKXPaymentTransactionPaystationEvent, "SKPaymentTransactionPaystationEvent", open) {
/// The Pay Station UI is about to be shown.
  SKXPaymentTransactionPaystationEventWillOpen = 0,
/// The Pay Station UI became visible to the user.
  SKXPaymentTransactionPaystationEventOpened = 1,
/// The Pay Station page finished its initial load.
  SKXPaymentTransactionPaystationEventLoaded = 2,
/// The Pay Station UI is about to close.
  SKXPaymentTransactionPaystationEventWillClose = 3,
/// The Pay Station UI was dismissed.
  SKXPaymentTransactionPaystationEventClosed = 4,
/// The Pay Station flow asked the system browser to open (external redirect).
  SKXPaymentTransactionPaystationEventOpenedExternally = 5,
};

/// Represents the state of a payment transaction in the Xsolla Mobile SDK.
/// Indicates the current status of a transaction in the payment process.
typedef SWIFT_ENUM(NSInteger, SKPaymentTransactionState, open) {
/// The transaction is being processed.
  SKPaymentTransactionStatePurchasing = 0,
/// The transaction has been successfully completed.
  SKPaymentTransactionStatePurchased = 1,
/// The transaction failed.
  SKPaymentTransactionStateFailed = 2,
/// The transaction was restored from a previous purchase.
  SKPaymentTransactionStateRestored = 3,
/// The transaction is deferred (awaiting approval).
  SKPaymentTransactionStateDeferred = 4,
};

/// Represents the size for the paystation UI.
/// Controls the dimensions of the payment interface.
typedef SWIFT_ENUM(NSInteger, SKPaystationSize, open) {
/// Small size for the paystation UI.
  SKPaystationSizeSmall = 0,
/// Medium size for the paystation UI.
  SKPaystationSizeMedium = 1,
/// Large size for the paystation UI.
  SKPaystationSizeLarge = 2,
};

/// Represents the theme for the paystation UI.
/// Controls the visual appearance of the payment interface.
typedef SWIFT_ENUM(NSInteger, SKPaystationTheme, open) {
/// Default theme.
  SKPaystationThemeDefault = 0,
/// Light theme.
  SKPaystationThemeLight = 1,
/// Dark theme.
  SKPaystationThemeDark = 2,
/// Custom theme.
  SKPaystationThemeOther = 3,
/// Automatically selects light or dark theme based on system settings.
  SKPaystationThemeAuto = 4,
};

@class NSDecimalNumber;
@class SKXProductDiscount;
/// Represents a product available for purchase in the Xsolla Mobile SDK.
/// Contains information about a product such as its identifier, description, and price.
SWIFT_CLASS_NAMED("SKProduct")
@interface SKXProduct : NSObject
/// The unique identifier for the product.
@property (nonatomic, readonly, copy) NSString * _Nonnull productIdentifier;
/// The localized description of the product.
@property (nonatomic, readonly, copy) NSString * _Nonnull localizedDescription;
/// The localized title of the product.
@property (nonatomic, readonly, copy) NSString * _Nonnull localizedTitle;
/// The price of the product.
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nonnull price;
/// The locale for the product’s price.
@property (nonatomic, readonly, copy) NSLocale * _Nonnull priceLocale;
/// The localized string representation of the product price, suitable for display.
/// Formats the price according to the locale and currency.
@property (nonatomic, readonly, copy) NSString * _Nonnull displayPrice;
/// Image URL of the product, this is an extension API, StoreKit doesn’t support this
@property (nonatomic, readonly, copy) NSURL * _Nullable imageUrl;
/// The introductory price for the product, if available.
@property (nonatomic, readonly, strong) SKXProductDiscount * _Nullable introductoryPrice;
/// The discounts available for the product.
@property (nonatomic, readonly, copy) NSArray<SKXProductDiscount *> * _Nonnull discounts;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents a discount for a product in the Xsolla Mobile SDK.
/// Contains information about a discount such as its price and type.
SWIFT_CLASS_NAMED("SKProductDiscount")
@interface SKXProductDiscount : NSObject
/// The unique identifier for the discount.
@property (nonatomic, readonly, copy) NSString * _Nullable identifier;
/// The discounted price.
@property (nonatomic, readonly, strong) NSDecimalNumber * _Nonnull price;
/// The locale for the discount’s price.
@property (nonatomic, readonly, copy) NSLocale * _Nonnull priceLocale;
/// The localized string representation of the discount price, suitable for display.
/// Formats the price according to the locale and currency.
@property (nonatomic, readonly, copy) NSString * _Nonnull displayPrice;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Base class for requests in the Xsolla Mobile SDK.
/// Provides basic functionality for starting and canceling requests.
SWIFT_CLASS_NAMED("SKRequest")
@interface SKXRequest : NSObject
/// Starts the request.
/// Subclasses should override this method to implement their specific request logic.
- (void)start;
/// Cancels the request.
/// Subclasses should override this method to implement cancellation logic.
- (void)cancel;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol SKXProductsRequestDelegate;
/// Handles requests for loading products from the Xsolla store.
/// Used to fetch product information that can be presented to users for purchase.
SWIFT_CLASS_NAMED("SKProductsRequest")
@interface SKXProductsRequest : SKXRequest
/// The delegate that receives callbacks when the request completes or fails.
@property (nonatomic, weak) id <SKXProductsRequestDelegate> _Nullable delegate;
/// Initializes a new instance of <code>SKProductsRequest</code>.
/// \param productIdentifiers The product identifiers to request.
///
- (nonnull instancetype)initWithProductIdentifiers:(NSSet<NSString *> * _Nonnull)productIdentifiers OBJC_DESIGNATED_INITIALIZER;
/// Starts the products request.
/// This initiates the fetch of product information from the Xsolla store.
- (void)start;
/// Cancels the products request.
/// This stops the fetch of product information if it’s still in progress.
- (void)cancel;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Protocol for handling requests in the Xsolla Mobile SDK.
/// This delegate receives callbacks when requests complete or fail.
SWIFT_PROTOCOL_NAMED("SKRequestDelegate")
@protocol SKXRequestDelegate
@optional
/// Called when the request successfully completes.
/// \param request The request that finished.
///
- (void)requestDidFinish:(SKXRequest * _Nonnull)request;
/// Called when the request fails with an error.
/// \param request The request that failed.
///
/// \param error The error that occurred during the request.
///
- (void)request:(SKXRequest * _Nonnull)request didFailWithError:(NSError * _Nonnull)error;
@end

@class SKXProductsResponse;
/// Protocol for handling product requests in the Xsolla Mobile SDK.
/// Implement this protocol to receive callbacks when product requests complete or fail.
SWIFT_PROTOCOL_NAMED("SKProductsRequestDelegate")
@protocol SKXProductsRequestDelegate <SKXRequestDelegate>
/// Called when the products request receives a response.
/// This method is invoked with the requested product information.
/// \param request The products request that received the response.
///
/// \param response The response containing the requested products.
///
- (void)productsRequest:(SKXProductsRequest * _Nonnull)request didReceiveResponse:(SKXProductsResponse * _Nonnull)response;
@end

/// Represents the response for a products request in the Xsolla Mobile SDK.
/// Contains the requested products and any invalid product identifiers.
SWIFT_CLASS_NAMED("SKProductsResponse")
@interface SKXProductsResponse : NSObject
/// The products that were successfully retrieved.
/// These products can be presented to users for purchase.
@property (nonatomic, readonly, copy) NSArray<SKXProduct *> * _Nonnull products;
/// The product identifiers that were not found.
/// These identifiers did not match any available products.
@property (nonatomic, readonly, copy) NSArray<NSString *> * _Nonnull invalidProductIdentifiers;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents an error in the Xsolla Mobile SDK.
/// This class extends NSError to provide specific error codes and information.
SWIFT_CLASS("_TtC15XsollaMobileSDK8SKXError")
@interface SKXError : NSError
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
@property (nonatomic, readonly, copy) NSString * _Nonnull description;
@property (nonatomic, readonly, copy) NSString * _Nonnull localizedDescription;
- (nonnull instancetype)initWithDomain:(NSString * _Nonnull)domain code:(NSInteger)code userInfo:(NSDictionary<NSString *, id> * _Nullable)dict SWIFT_UNAVAILABLE;
@end

/// Container for initiating a token-only Pay Station purchase.
/// <ul>
///   <li>
///     <code>isSandbox</code> defaults to <code>nil</code>. If <code>nil</code>, the value from current <code>SKPaymentSettings.useSandbox</code> is used.
///   </li>
/// </ul>
SWIFT_CLASS_NAMED("TokenPayment")
@interface XMTokenPayment : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull paystationToken;
/// [DEPRECATED] Сontrols whether a finished status from Pay Station is enough to
/// mark the transaction as successful when no <code>order_id</code>/SKU is present. Defaults to <code>false</code>.
/// See token creation API: https://developers.xsolla.com/api/shop-builder/operation/admin-create-payment-token/
@property (nonatomic) BOOL allowFinishedWithoutOrderId SWIFT_DEPRECATED_MSG("Deprecated");
- (nonnull instancetype)initWithPaystationToken:(NSString * _Nonnull)paystationToken;
- (nonnull instancetype)initWithPaystationToken:(NSString * _Nonnull)paystationToken isSandbox:(BOOL)isSandbox;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents authorization information in an Objective-C compatible format.
SWIFT_CLASS("_TtC15XsollaMobileSDK17XMAccessTokenInfo")
@interface XMAccessTokenInfo : NSObject
/// User JWT.
@property (nonatomic, readonly, copy) NSString * _Nonnull accessToken;
/// JWT expiration date.
@property (nonatomic, readonly, copy) NSDate * _Nullable expiresIn;
/// Refresh token for updating the <code>accessToken</code>.
@property (nonatomic, readonly, copy) NSString * _Nullable refreshToken;
/// JWT type. Can be <em>bearer</em>.
@property (nonatomic, readonly, copy) NSString * _Nonnull tokenType;
/// Initializes <code>XMAccessTokenInfo</code> with specified parameters.
/// \param accessToken The access token string.
///
/// \param expiresIn The expiration date of the token.
///
/// \param refreshToken The refresh token string.
///
/// \param tokenType The type of the token.
///
- (nonnull instancetype)initWithAccessToken:(NSString * _Nonnull)accessToken expiresIn:(NSDate * _Nullable)expiresIn refreshToken:(NSString * _Nullable)refreshToken tokenType:(NSString * _Nonnull)tokenType OBJC_DESIGNATED_INITIALIZER;
/// Converts the access token information to a JSON string.
///
/// returns:
/// A JSON string representation of the access token information, or <code>nil</code> if encoding fails.
- (NSString * _Nullable)toJsonString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

/// Represents social network providers for authentication (Objective-C compatible).
typedef SWIFT_ENUM(NSInteger, XMSocialNetworkProvider, open) {
  XMSocialNetworkProviderXsolla = 0,
  XMSocialNetworkProviderEpicgames = 1,
};

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
